# Generated by Django 5.1.6 on 2025-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('or', 'Odia'), ('ur', 'Urdu'), ('as', 'Assamese'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh-cn', 'Chinese'), ('ja', 'Japanese'), ('ru', 'Russian')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
