# Generated by Django 5.1.6 on 2025-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
